### ISSUE TITLE
Net 5.0: BinaryFormatter serialization and deserialization are disabled within this application

### ISSUE THREAD

**Issue by luisabreu** [nhibernate/fluent-nhibernate#479]
Hello.

I'm trying to migrate an existing app to net 5.0 and it seems like there's an issue with FluentNhibernate and binary serialization:

```
System.NotSupportedException: BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at FluentNHibernate.Utils.Extensions.DeepClone[T](T obj)
   at FluentNHibernate.Mapping.SubclassMap`1.FluentNHibernate.Mapping.Providers.IIndeterminateSubclassMappingProvider.GetSubclassMapping(SubclassType type)
   at FluentNHibernate.Visitors.SeparateSubclassVisitor.ProcessClass(ClassMapping mapping)
   at FluentNHibernate.MappingModel.ClassBased.ClassMapping.AcceptVisitor(IMappingModelVisitor visitor)
   at FluentNHibernate.Visitors.DefaultMappingModelVisitor.Visit(ClassMapping classMapping)
   at FluentNHibernate.MappingModel.HibernateMapping.AcceptVisitor(IMappingModelVisitor visitor)
   at FluentNHibernate.Visitors.DefaultMappingModelVisitor.<Visit>b__10_0(HibernateMapping x)
   at FluentNHibernate.Utils.CollectionExtensions.Each[T](IEnumerable`1 enumerable, Action`1 each)
   at FluentNHibernate.Visitors.DefaultMappingModelVisitor.Visit(IEnumerable`1 mappings)
   at FluentNHibernate.PersistenceModel.ApplyVisitors(IEnumerable`1 mappings)
   at FluentNHibernate.PersistenceModel.BuildMappings()
   at FluentNHibernate.PersistenceModel.EnsureMappingsBuilt()
   at FluentNHibernate.PersistenceModel.Configure(Configuration cfg)
   at FluentNHibernate.Cfg.FluentConfiguration.BuildConfiguration()
   --- End of inner exception stack trace ---
   at FluentNHibernate.Cfg.FluentConfiguration.BuildConfiguration()
   at FluentNHibernate.Cfg.FluentConfiguration.BuildSessionFactory()
```

For now, we can use the `EnableUnsaveBinaryFormatterSerialization` entry on the csproj file:

```xml
<EnableUnsafeBinaryFormatterSerialization>false</EnableUnsafeBinaryFormatterSerialization>
```

Will FluentNhibernate be ported to net 5.0? Will it change its internals?

Thanks.

**Comment by oyzar** [comment]
It looks like BinaryFormatter is used one place in FluentNHibernate and 5 places in NHibernate... EnableUnsafeBinaryFormatterSerialization is just as unsafe as not upgrading, so this need a security patch regardless.

**Comment by luisabreu** [comment]
Yes, but is there a way to configure Fluent NHiobernate so that it doesn't use it?

**Comment by hazzik** [comment]
Not at the moment. I'll work on a fix later today.

**Comment by luisabreu** [comment]
Ok, Great news then 👍

**Comment by hazzik** [comment]
This should be fixed. Please check 3.1.0

**Comment by luisabreu** [comment]
Yes, no longer throws an exception here. Great job guys!

**Comment by cremor** [comment]
3.1.0 was released on NuGet and tagged in the repo but no release was created on GitHub. Is this on purpose?

**Comment by hazzik** [comment]
@cremor should have been done automatically. Probably a bug in the build process. I published the release (it was in a draft state).
